### ISSUE TITLE
Worldbuilding Task #210131

### ISSUE THREAD

**Issue by zuedev** [zuedev/monorepo#5]
### Brief

We need to write some content for BBG to establish the setting that the super top-secret random-dungeon-diving project will be using. The best place for this project to take place in is probably Cragview Cove, as the Empire is a typical human-led organisation that players will already be accustomed to. The Gilded Coast is also a great place for mercenaries to help out the state with tasks like this as gold is king there.

### Tasks
- [ ] Write the history of Cragview Cove @NotRados 
- [ ] Write about how the blight came to Cragview Cove @notLoonah 
- [ ] Write about the response to the Cragview Cove blight @zuedev 

### Sources

- [Gilded Coast Map (2020)](https://gitlab.com/zuedev/travellers-guide-to-eldragiir/-/raw/review/assets/haven_gildedcoast.png)

**Comment by zuedev** [comment]
We came up with this idea for the walls/checkpoint positions:
![image](https://user-images.githubusercontent.com/24614929/107081222-4609fd00-67ea-11eb-9b6d-0901eeb60838.png)

**Comment by zuedev** [comment]
Closing in favour of private kanban planning
